In [2]:
import pandas as pd

In [3]:
pd.options.display.float_format = '{:.2f}'.format

In [4]:
df = pd.read_csv("Retail_Store_Data.csv")

In [6]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.96,2,0.00,41.91
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.94,3,0.00,219.58
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.62,2,0.00,6.87
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.58,5,0.45,-383.03
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.37,2,0.20,2.52

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

In [8]:
df.describe()

       Postal Code    Sales  Quantity  Discount   Profit
count      9994.00  9994.00   9994.00   9994.00  9994.00
mean      55190.38   229.86      3.79      0.16    28.66
std       32063.69   623.25      2.23      0.21   234.26
min        1040.00     0.44      1.00      0.00 -6599.98
25%       23223.00    17.28      2.00      0.00     1.73
50%       56430.50    54.49      3.00      0.20     8.67
75%       90008.00   209.94      5.00      0.20    29.36
max       99301.00 22638.48     14.00      0.80  8399.98

In [9]:
df.shape

(9994, 13)

In [10]:
df.duplicated().sum()

np.int64(17)

In [11]:
df[df.duplicated(keep = False)].sort_values(by = list(df.columns)).head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
6409,First Class,Consumer,United States,Houston,Texas,77041,Central,Office Supplies,Paper,47.95,3,0.20,16.18
8032,First Class,Consumer,United States,Houston,Texas,77041,Central,Office Supplies,Paper,47.95,3,0.20,16.18
5493,Same Day,Home Office,United States,San Francisco,California,94122,West,Office Supplies,Labels,41.40,4,0.00,19.87
5905,Same Day,Home Office,United States,San Francisco,California,94122,West,Office Supplies,Labels,41.40,4,0.00,19.87
2807,Second Class,Consumer,United States,Seattle,Washington,98115,West,Office Supplies,Paper,12.96,2,0.00,6.22

In [12]:
df.drop_duplicates(inplace = True)

In [13]:
df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [14]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [15]:
df.columns = df.columns.str.replace('-', '_')

In [16]:
df.columns

Index(['ship_mode', 'segment', 'country', 'city', 'state', 'postal_code',
       'region', 'category', 'sub_category', 'sales', 'quantity', 'discount',
       'profit'],
      dtype='object')

In [17]:
df.groupby('category')['sales'].sum().sort_values(ascending=False)

category
Technology        836154.03
Furniture         741306.31
Office Supplies   718735.24
Name: sales, dtype: float64

In [18]:
df.groupby('region')['sales'].sum().sort_values(ascending=False)

region
West      725255.64
East      678435.20
Central   500782.85
South     391721.91
Name: sales, dtype: float64

In [19]:
df.groupby('segment')['sales'].sum().sort_values(ascending=False)

segment
Consumer      1160832.77
Corporate      706070.13
Home Office    429292.68
Name: sales, dtype: float64

In [20]:
df.groupby('category')['profit'].sum().sort_values(ascending=False)

category
Technology        145454.95
Office Supplies   122364.66
Furniture          18421.81
Name: profit, dtype: float64

In [21]:
df.groupby('sub_category')['profit'].sum().sort_values(ascending=False)

sub_category
Copiers        55617.82
Phones         44515.73
Accessories    41936.64
Paper          33944.24
Binders        30228.00
Chairs         26567.13
Storage        21278.83
Appliances     18138.01
Furnishings    13052.72
Envelopes       6964.18
Art             6524.61
Labels          5526.38
Machines        3384.76
Fasteners        949.52
Supplies       -1189.10
Bookcases      -3472.56
Tables        -17725.48
Name: profit, dtype: float64

In [22]:
df.groupby('sub_category')['sales'].sum().sort_values(ascending=False)

sub_category
Phones        330007.05
Chairs        327777.76
Storage       223843.61
Tables        206965.53
Binders       203409.17
Machines      189238.63
Accessories   167380.32
Copiers       149528.03
Bookcases     114880.00
Appliances    107532.16
Furnishings    91683.02
Paper          78224.14
Supplies       46673.54
Art            27107.03
Envelopes      16476.40
Labels         12444.91
Fasteners       3024.28
Name: sales, dtype: float64

In [23]:
df[df['sub_category'] == 'Tables'].groupby('discount')['profit'].mean()

discount
0.00    184.39
0.20     -4.28
0.30    -63.01
0.40   -215.83
0.45   -226.65
0.50   -239.32
Name: profit, dtype: float64

In [24]:
df.groupby('region')['profit'].sum().sort_values(ascending=False)

region
West      108329.81
East       91506.31
South      46749.43
Central    39655.88
Name: profit, dtype: float64

In [25]:
df.groupby('discount')['profit'].mean()

discount
0.00     67.02
0.10     96.06
0.15     27.29
0.20     24.72
0.30    -45.83
0.32    -88.56
0.40   -111.93
0.45   -226.65
0.50   -310.70
0.60    -43.08
0.70    -95.87
0.80   -102.12
Name: profit, dtype: float64

In [54]:
df.groupby('sub_category')['sales'].sum().sort_values(ascending=False).head(5)

sub_category
Phones    330007.05
Chairs    327777.76
Storage   223843.61
Tables    206965.53
Binders   203409.17
Name: sales, dtype: float64

In [59]:
df.to_csv("clean_retail_data.csv", index=False)